name:                fltkhs-themes-demo
version:             0.1.0.0
github:              "deech/fltkhs-themes-demo"
license:             BSD3
author:              "Aditya Siram"
maintainer:          "aditya.siram@gmail.com"
copyright:           "2018 Aditya Siram"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/deech/fltkhs-themes-demo#readme>

dependencies:
- base >= 4.7 && < 5

flags:
  fastCompile:
    description: Turn off optimizations for faster compilation
    manual: True
    default: False

executables:
  fltkhs-simple-theme-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Werror
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - fltkhs >= 0.5.4.4
      - fltkhs-themes >= 0.1.0.0
      - text >= 1.2.2.0
      - load-font >= 0.1.0.0
    when:
      - condition: impl(ghc >= 7.10) && impl(ghc < 8.0) && flag(fastCompile)
        then:
          ghc-options: -fno-specialise -fmax-simplifier-iterations=0 -fsimplifier-phases=0
        else:
          ghc-options: -O2
      - condition: (os(linux) || os(windows))
        then:
          ghc-options: -pgml g++ "-optl-Wl,--allow-multiple-definition" "-optl-Wl,--whole-archive" "-optl-Wl,-Bstatic" "-optl-Wl,-lfltkc" "-optl-Wl,-Bdynamic" "-optl-Wl,--no-whole-archive"
        else:
          ghc-options: "-optl-Wl,-lfltkc"
