name:                fltkhs-themes-demo
version:             0.1.0.0
github:              "deech/fltkhs-themes-demo"
license:             BSD3
author:              "Aditya Siram"
maintainer:          "aditya.siram@gmail.com"
copyright:           "2018 Aditya Siram"
data-files:
- images/*.png
extra-source-files:
- README.md
description:         Please see the README on Github at <https://github.com/deech/fltkhs-themes-demo#readme>

custom-setup:
  dependencies:
  - base >= 4.4
  - Cabal >= 2.2.0.0 && < 3
  - asset-bundle >= 0.1.0.1
  - filepath
  - directory

dependencies:
- base >= 4.7 && < 5

flags:
  fastCompile:
    description: Turn off optimizations for faster compilation
    manual: True
    default: False

executables:
  fltkhs-light-theme-demo:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - fltkhs >= 0.7.0.2
      - fltkhs-themes >= 0.1.0.4
      - text >= 1.2.2.0
      - load-font >= 0.1.0.2
    when:
      - condition: impl(ghc >= 7.10) && impl(ghc < 8.0) && flag(fastCompile)
        then:
          ghc-options: -fno-specialise -fmax-simplifier-iterations=0 -fsimplifier-phases=0
        else:
          ghc-options: -O2
      - condition: (os(linux) || os(windows))
        then:
          ghc-options: -pgml g++ "-optl-Wl,--allow-multiple-definition" "-optl-Wl,--whole-archive" "-optl-Wl,-Bstatic" "-optl-Wl,-lfltkc" "-optl-Wl,-Bdynamic" "-optl-Wl,--no-whole-archive"
        else:
          ghc-options: "-optl-Wl,-lfltkc"
